services:
  - type: background
    name: fcb-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: COINGECKO_API_KEY
        sync: false

